//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElanWaveBookstore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Book
    {
        [Key]
        public int BookID { get; set; }

        [Required(ErrorMessage ="  Invalid ISBN")]
        [MinLength(13), MaxLength(13)]
        [Display(Name = "ISBN*")]
        public string ISBN { get; set; }

        [Required(ErrorMessage = "  Cannot be empty!")]
        [Display(Name = "Title*")]
        public string Title { get; set; }

        [Required(ErrorMessage = "  Cannot be empty!")]
        [Display(Name = "Author*")]
        public string Author { get; set; }

        [Required(ErrorMessage = "  Cannot be empty!")]
        [Display(Name = "Genre*")]
        public string Genre { get; set; }

        public byte IsDeleted { get; set; }
    }
}
