//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElanWaveBookstore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Net.Http;

    public partial class User
    {
        [Key]
        public int UserAccountID { get; set; }

        [Required]
        [Display(Name = "Username*")]
        //[System.Web.Mvc.Remote("IsAlreadySigned", "User", HttpMethod = "POST", ErrorMessage = "This username is taken!.")]
        public string Username { get; set; }

        [Required]
        [Display(Name = "Password*")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        [Display(Name = "Repeat password*")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Passwords do not match.")]
        public string RepeatedPassword { get; set; }

        public byte IsDeleted { get; set; }
    }
}
